var data = [
	{country: "United States", confederation: "CONCACAF", population: 324, audience: 137.6, gdp: 8735},
	{country: "Japan", confederation: "AFC", population: 136.8, audience: 156.8, gdp: 7034},
	{country: "China", confederation: "AFC", population: 1404, audience: 473.6, gdp: 5643},
	{country: "Germany", confederation: "UEFA", population: 86.4, audience: 92.8, gdp: 4870},
	{country: "Brazil", confederation: "CONMEBOL", population: 201.6, audience: 227.2, gdp: 4174},
	{country: "United Kingdom", confederation: "UEFA", population: 64.8, audience: 67.2, gdp: 3247},
	{country: "Italy", confederation: "UEFA", population: 64.8, audience: 67.2, gdp: 3092},
	{country: "France", confederation: "UEFA", population: 64.8, audience: 64, gdp: 3092},
	{country: "Russia", confederation: "UEFA", population: 151.2, audience: 99.2, gdp: 2706},
	{country: "Spain", confederation: "UEFA", population: 50.4, audience: 57.6, gdp: 2396},
	{country: "South Korea", confederation: "AFC", population: 50.4, audience: 57.6, gdp: 2319},
	{country: "Indonesia", confederation: "AFC", population: 252, audience: 214.4, gdp: 2242},
	{country: "Mexico", confederation: "CONCACAF", population: 122.4, audience: 102.4, gdp: 2010},
	{country: "Turkey", confederation: "UEFA", population: 79.2, audience: 73.6, gdp: 1546},
	{country: "Thailand", confederation: "AFC", population: 72, audience: 76.8, gdp: 1237},
	{country: "Argentina", confederation: "CONMEBOL", population: 43.2, audience: 48, gdp: 1237},
	{country: "Netherlands", confederation: "UEFA", population: 14.4, audience: 19.2, gdp: 1160},
	{country: "Poland", confederation: "UEFA", population: 43.2, audience: 38.4, gdp: 1005},
	{country: "Saudi Arabia", confederation: "AFC", population: 28.8, audience: 16, gdp: 928},
	{country: "Taiwan", confederation: "AFC", population: 21.6, audience: 16, gdp: 773},
	{country: "Canada", confederation: "CONCACAF", population: 36, audience: 16, gdp: 773},
	{country: "Colombia", confederation: "CONMEBOL", population: 50.4, audience: 51.2, gdp: 696},
	{country: "Venezuela", confederation: "CONMEBOL", population: 28.8, audience: 32, gdp: 696},
	{country: "South Africa", confederation: "CAF", population: 50.4, audience: 41.6, gdp: 618},
	{country: "Malaysia", confederation: "AFC", population: 28.8, audience: 22.4, gdp: 541},
	{country: "Switzerland", confederation: "UEFA", population: 7.2, audience: 9.6, gdp: 541},
	{country: "Nigeria", confederation: "CAF", population: 165.6, audience: 83.2, gdp: 541},
	{country: "Belgium", confederation: "UEFA", population: 14.4, audience: 9.6, gdp: 541},
	{country: "Sweden", confederation: "UEFA", population: 7.2, audience: 9.6, gdp: 541},
	{country: "Vietnam", confederation: "AFC", population: 93.6, audience: 83.2, gdp: 464},
	{country: "Iran", confederation: "AFC", population: 79.2, audience: 22.4, gdp: 464},
	{country: "Chile", confederation: "CONMEBOL", population: 21.6, audience: 19.2, gdp: 464},
	{country: "Romania", confederation: "UEFA", population: 21.6, audience: 22.4, gdp: 464},
	{country: "Austria", confederation: "UEFA", population: 7.2, audience: 9.6, gdp: 464},
	{country: "Singapore", confederation: "AFC", population: 7.2, audience: 6.4, gdp: 464},
	{country: "Australia", confederation: "AFC", population: 21.6, audience: 9.6, gdp: 387},
	{country: "Greece", confederation: "UEFA", population: 14.4, audience: 9.6, gdp: 387},
	{country: "Portugal", confederation: "UEFA", population: 14.4, audience: 12.8, gdp: 387},
	{country: "India", confederation: "AFC", population: 1267.2, audience: 64, gdp: 387},
	{country: "Czech Republic", confederation: "UEFA", population: 14.4, audience: 9.6, gdp: 387},
	{country: "Egypt", confederation: "CAF", population: 79.2, audience: 25.6, gdp: 387},
	{country: "Denmark", confederation: "UEFA", population: 7.2, audience: 6.4, gdp: 387},
	{country: "Norway", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 309},
	{country: "Peru", confederation: "CONMEBOL", population: 28.8, audience: 25.6, gdp: 309},
	{country: "Ukraine", confederation: "UEFA", population: 50.4, audience: 28.8, gdp: 309},
	{country: "Iraq", confederation: "AFC", population: 36, audience: 16, gdp: 309},
	{country: "Hungary", confederation: "UEFA", population: 7.2, audience: 9.6, gdp: 309},
	{country: "Kazakhstan", confederation: "UEFA", population: 14.4, audience: 9.6, gdp: 232},
	{country: "Finland", confederation: "UEFA", population: 7.2, audience: 6.4, gdp: 232},
	{country: "Ireland", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 232},
	{country: "Algeria", confederation: "CAF", population: 36, audience: 12.8, gdp: 232},
	{country: "Cuba", confederation: "CONCACAF", population: 14.4, audience: 9.6, gdp: 232},
	{country: "Ecuador", confederation: "CONMEBOL", population: 14.4, audience: 16, gdp: 232},
	{country: "Slovakia", confederation: "UEFA", population: 7.2, audience: 6.4, gdp: 232},
	{country: "Qatar", confederation: "AFC", population: 2.3, audience: 1.6, gdp: 155},
	{country: "Kuwait", confederation: "AFC", population: 3.7, audience: 3.2, gdp: 155},
	{country: "Bulgaria", confederation: "UEFA", population: 7.2, audience: 6.4, gdp: 155},
	{country: "Serbia", confederation: "UEFA", population: 7.2, audience: 9.6, gdp: 155},
	{country: "Belarus", confederation: "UEFA", population: 7.2, audience: 6.4, gdp: 155},
	{country: "Hong Kong", confederation: "AFC", population: 7.2, audience: 3.2, gdp: 155},
	{country: "Croatia", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Oman", confederation: "AFC", population: 4.1, audience: 0.8, gdp: 77},
	{country: "Dominica Republic", confederation: "CONCACAF", population: 7.2, audience: 6.4, gdp: 77},
	{country: "Azerbaijan", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 77},
	// {country: "New Zealand", confederation: "OFC", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Lithuania", confederation: "UEFA", population: 2.9, audience: 3.2, gdp: 77},
	{country: "Slovenia", confederation: "UEFA", population: 2.1, audience: 3.2, gdp: 77},
	{country: "Uruguay", confederation: "CONMEBOL", population: 3.4, audience: 3.2, gdp: 77},
	{country: "Costa Rica", confederation: "CONCACAF", population: 7.2, audience: 6.4, gdp: 77},
	{country: "Uzbekistan", confederation: "AFC", population: 28.8, audience: 16, gdp: 77},
	{country: "Yemen", confederation: "CAF", population: 21.6, audience: 12.8, gdp: 77},
	{country: "Israel", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 77},
	{country: "El Salvador", confederation: "CONCACAF", population: 7.2, audience: 6.4, gdp: 77},
	{country: "Syria", confederation: "AFC", population: 21.6, audience: 9.6, gdp: 77},
	{country: "Pakistan", confederation: "AFC", population: 180, audience: 12.8, gdp: 77},
	{country: "Guatemala", confederation: "CONCACAF", population: 14.4, audience: 6.4, gdp: 77},
	{country: "Paraguay", confederation: "CONMEBOL", population: 7.2, audience: 6.4, gdp: 77},
	{country: "Panama", confederation: "CONCACAF", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Bosnia-Herzegovina", confederation: "UEFA", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Cambodia", confederation: "AFC", population: 14.4, audience: 16, gdp: 77},
	{country: "Ivory Coast", confederation: "CAF", population: 21.6, audience: 12.8, gdp: 77},
	{country: "Latvia", confederation: "UEFA", population: 2, audience: 3.2, gdp: 77},
	{country: "Lebanon", confederation: "AFC", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Jordan", confederation: "AFC", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Honduras", confederation: "CONCACAF", population: 7.2, audience: 9.6, gdp: 77},
	{country: "Brunei", confederation: "AFC", population: 0.4, audience: 0.8, gdp: 77},
	{country: "Albania", confederation: "UEFA", population: 3, audience: 3.2, gdp: 77},
	{country: "Turkmenistan", confederation: "AFC", population: 7.2, audience: 3.2, gdp: 77},
	{country: "Angola", confederation: "CAF", population: 21.6, audience: 3.2, gdp: 77},
	{country: "Nepal", confederation: "AFC", population: 28.8, audience: 12.8, gdp: 77},
	{country: "Ghana", confederation: "CAF", population: 28.8, audience: 6.4, gdp: 77},
	{country: "Macedonia", confederation: "UEFA", population: 2.1, audience: 3.2, gdp: 39},
	{country: "Kenya", confederation: "CAF", population: 43.2, audience: 9.6, gdp: 15},
	{country: "Philippines", confederation: "AFC", population: 100.8, audience: 3.2, gdp: 46},
	{country: "Bolivia", confederation: "CONMEBOL", population: 7.2, audience: 3.2, gdp: 8},
	{country: "Afghanistan", confederation: "AFC", population: 28.8, audience: 9.6, gdp: 31},
	{country: "Myanmar", confederation: "AFC", population: 57.6, audience: 3.2, gdp: 31},
	{country: "Bangladesh", confederation: "AFC", population: 158.4, audience: 3.2, gdp: 77},
	{country: "Tanzania", confederation: "CAF", population: 50.4, audience: 3.2, gdp: 15},
	{country: "Ethiopia", confederation: "CAF", population: 93.6, audience: 6.4, gdp: 77},
	{country: "Congo DR", confederation: "CAF", population: 64.8, audience: 6.4, gdp: 46}
];